name: PR Title JIRA Check

on:
  pull_request:
    types: 
      - opened
      - reopened
      - ready_for_review
      - edited
      - synchronize
  merge_group:
    types: [checks_requested]

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title for JIRA Ticket
        run: |
          TITLE="${{ github.event.pull_request.title }}"
          REGEX="[A-Z]+-[0-9]+"
          if [[ ! "$TITLE" =~ $REGEX ]]; then
            echo "Pull Request title does not start with a JIRA ticket number (e.g., FOO-123)."
            exit 1
          fi
